"""add relationship between user and note

Revision ID: 81667a168fa3
Revises: 98967379f929
Create Date: 2025-08-16 11:09:37.027360

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81667a168fa3"
down_revision: Union[str, Sequence[str], None] = "98967379f929"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("note", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "note", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "note", type_="foreignkey")
    op.drop_column("note", "user_id")
    # ### end Alembic commands ###
